### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by mrshankly** [mrshankly/go-twitch#1]
### [Blocks](https://github.com/justintv/Twitch-API/blob/master/v3_resources/blocks.md) (1/3)
- [x] [`GET /users/:login/blocks`](https://github.com/justintv/Twitch-API/blob/master/v3_resources/blocks.md#get-usersloginblocks)
- [ ] [`PUT /users/:user/blocks/:target`](https://github.com/justintv/Twitch-API/blob/master/v3_resources/blocks.md#put-usersuserblockstarget)
- [ ] [`DELETE /users/:user/blocks/:target`](https://github.com/justintv/Twitch-API/blob/master/v3_resources/blocks.md#delete-usersuserblockstarget)
### [Channels](https://github.com/justintv/Twitch-API/blob/master/v3_resources/channels.md) (5/8)
- [x] [`GET /channels/:channel`](https://github.com/justintv/Twitch-API/blob/master/v3_resources/channels.md#get-channelschannel)
- [x] [`GET /channel`](https://github.com/justintv/Twitch-API/blob/master/v3_resources/channels.md#get-channel)
- [x] [`GET /channels/:channel/editors`](https://github.com/justintv/Twitch-API/blob/master/v3_resources/channels.md#get-channelschanneleditors)
- [ ] [`PUT /channels/:channel`](https://github.com/justintv/Twitch-API/blob/master/v3_resources/channels.md#put-channelschannel)
- [x] [`GET /channels/:channel/videos`](https://github.com/justintv/Twitch-API/blob/master/v3_resources/channels.md#get-channelschannelvideos)
- [x] [`GET /channels/:channel/follows`](https://github.com/justintv/Twitch-API/blob/master/v3_resources/channels.md#get-channelschannelfollows)
- [ ] [`DELETE /channels/:channel/stream_key`](https://github.com/justintv/Twitch-API/blob/master/v3_resources/channels.md#delete-channelschannelstream_key)
- [ ] [`POST /channels/:channel/commercial`](https://github.com/justintv/Twitch-API/blob/master/v3_resources/channels.md#post-channelschannelcommercial)
### [Chat](https://github.com/justintv/Twitch-API/blob/master/v3_resources/chat.md) (2/2)
- [x] [`GET /chat/:channel`](https://github.com/justintv/Twitch-API/blob/master/v3_resources/chat.md#get-chatchannel)
- [x] [`GET /chat/emoticons`](https://github.com/justintv/Twitch-API/blob/master/v3_resources/chat.md#get-chatemoticons)
### [Follows](https://github.com/justintv/Twitch-API/blob/master/v3_resources/follows.md) (4/6)
- [x] [`GET /channels/:channel/follows`](https://github.com/justintv/Twitch-API/blob/master/v3_resources/follows.md#get-channelschannelfollows)
- [x] [`GET /users/:user/follows/channels`](https://github.com/justintv/Twitch-API/blob/master/v3_resources/follows.md#get-usersuserfollowschannels)
- [x] [`GET /users/:user/follows/channels/:target`](https://github.com/justintv/Twitch-API/blob/master/v3_resources/follows.md#get-usersuserfollowschannelstarget)
- [ ] [`PUT /users/:user/follows/channels/:target`](https://github.com/justintv/Twitch-API/blob/master/v3_resources/follows.md#put-usersuserfollowschannelstarget)
- [ ] [`DELETE /users/:user/follows/channels/:target`](https://github.com/justintv/Twitch-API/blob/master/v3_resources/follows.md#delete-usersuserfollowschannelstarget)
- [x] [`GET /streams/followed`](https://github.com/justintv/Twitch-API/blob/master/v3_resources/users.md#get-streamsfollowed)
### [Games](https://github.com/justintv/Twitch-API/blob/master/v3_resources/games.md) (1/1)
- [x] [`GET /games/top`](https://github.com/justintv/Twitch-API/blob/master/v3_resources/games.md#get-gamestop)
### [Ingests](https://github.com/justintv/Twitch-API/blob/master/v3_resources/ingests.md) (1/1)
- [x] [`GET /ingests/`](https://github.com/justintv/Twitch-API/blob/master/v3_resources/ingests.md#get-ingests)
### [Search](https://github.com/justintv/Twitch-API/blob/master/v3_resources/search.md) (2/2)
- [x] [`GET /search/streams`](https://github.com/justintv/Twitch-API/blob/master/v3_resources/search.md#get-searchstreams)
- [x] [`GET /search/games`](https://github.com/justintv/Twitch-API/blob/master/v3_resources/search.md#get-searchgames)
### [Streams](https://github.com/justintv/Twitch-API/blob/master/v3_resources/streams.md) (5/5)
- [x] [`GET /streams/:channel/`](https://github.com/justintv/Twitch-API/blob/master/v3_resources/streams.md#get-streamschannel)
- [x] [`GET /streams`](https://github.com/justintv/Twitch-API/blob/master/v3_resources/streams.md#get-streams)
- [x] [`GET /streams/featured`](https://github.com/justintv/Twitch-API/blob/master/v3_resources/streams.md#get-streamsfeatured)
- [x] [`GET /streams/summary`](https://github.com/justintv/Twitch-API/blob/master/v3_resources/streams.md#get-streamssummary)
- [x] [`GET /streams/followed`](https://github.com/justintv/Twitch-API/blob/master/v3_resources/streams.md#get-streamsfollowed)
### [Subscriptions](https://github.com/justintv/Twitch-API/blob/master/v3_resources/subscriptions.md) (3/3)
- [x] [`GET /channels/:channel/subscriptions`](https://github.com/justintv/Twitch-API/blob/master/v3_resources/subscriptions.md#get-channelschannelsubscriptions)
- [x] [`GET /channels/:channel/subscriptions/:user`](https://github.com/justintv/Twitch-API/blob/master/v3_resources/subscriptions.md#get-channelschannelsubscriptionsuser)
- [x] [`GET /users/:user/subscriptions/:channel`](https://github.com/justintv/Twitch-API/blob/master/v3_resources/subscriptions.md#get-usersusersubscriptionschannel)
### [Teams](https://github.com/justintv/Twitch-API/blob/master/v3_resources/teams.md) (2/2)
- [x] [`GET /teams`](https://github.com/justintv/Twitch-API/blob/master/v3_resources/teams.md#get-teams)
- [x] [`GET /teams/:team`](https://github.com/justintv/Twitch-API/blob/master/v3_resources/teams.md#get-teamsteam)
### [Users](https://github.com/justintv/Twitch-API/blob/master/v3_resources/users.md) (4/4)
- [x] [`GET /users/:user`](https://github.com/justintv/Twitch-API/blob/master/v3_resources/users.md#get-usersuser)
- [x] [`GET /user`](https://github.com/justintv/Twitch-API/blob/master/v3_resources/users.md#get-user)
- [x] [`GET /streams/followed`](https://github.com/justintv/Twitch-API/blob/master/v3_resources/users.md#get-streamsfollowed)
- [x] [`GET /videos/followed`](https://github.com/justintv/Twitch-API/blob/master/v3_resources/users.md#get-videosfollowed)
### [Videos](https://github.com/justintv/Twitch-API/blob/master/v3_resources/videos.md) (4/4)
- [x] [`GET /videos/:id`](https://github.com/justintv/Twitch-API/blob/master/v3_resources/videos.md#get-videosid)
- [x] [`GET /videos/top`](https://github.com/justintv/Twitch-API/blob/master/v3_resources/videos.md#get-videostop)
- [x] [`GET /channels/:channel/videos`](https://github.com/justintv/Twitch-API/blob/master/v3_resources/videos.md#get-channelschannelvideos)
- [x] [`GET /videos/followed`](https://github.com/justintv/Twitch-API/blob/master/v3_resources/videos.md#get-videosfollowed)

**Comment by mrshankly** [comment]
Work is being done to update this library to [Twitch API V5](https://dev.twitch.tv/docs), see the [v5 branch](https://github.com/mrshankly/go-twitch/tree/v5).

I'm closing this since it's outdated.
